version: "3"
services:
  # Mongo DB for scorer
  # mongozexe:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   ports:
  #     - 27027:27017
  #   volumes:
  #     - ./data/dump:/dump
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  # Scorer Node
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - mongozexe
    ports:
      - "8090:3010"
    environment:
        # - MONGO_URL=mongodb://root:password@mongozexe:27017/?authMechanism=DEFAULT
        # - MONGO_URL=mongodb://root:password@mongozexe:27017/?directConnection=true&authSource=admin&replicaSet=replicaset&retryWrites=true
        - MONGO_URL=mongodb+srv://g-2-project-1:AzVr1gDMWsMc1lAN@cluster0.j1yrl.mongodb.net/zexe-arbitrum9-test?retryWrites=true&w=majority
        - MONGO_URL1=mongodb+srv://g-2-project-1:AzVr1gDMWsMc1lAN@cluster0.j1yrl.mongodb.net/zexe-test9-test?retryWrites=true&w=majority
        - WEB_3_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweERjZTFjMzYxYzgyNEI1ZjRFMzRGY2ZCNjUxMUYzNjkwNjc5RjhmODYiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2Njk4OTQyMTQ5NjMsIm5hbWUiOiJ6ZXhlLjAxIn0.YR1oAHiW_tA0lwG29tXz2wrYdTjWdCijto4yP_3uHHg
        - PRIVATE_KEY1=0x7cf03fae45cb10d4e3ba00a10deeacfc8cea1be0eebcfb7277a7df2e5074a405
        - PRIVATE_KEY2=0xcdb7f4e35a4443b45b8316666caa396b7a9f4686fcff1901c008b15a2fa2e904
        - EXCHANGE_ADD=0xC8a28C6EA6825428a5270F7e9070Cbe31E2cFDbf
  #     - PORT=${PORT}
  #     - ANALYSER_PORT=${ANALYSER_PORT}
  #     - ANALYSER_SERVER_STRING=analyser
  #     - COVALENT_API=${COVALENT_API}
  #     - MONGO_USER=${MONGO_USER}
  #     - MONGO_PWD=${MONGO_PWD}
  #     - MONGO_PORT=${MONGO_PORT}
  #     - DB_SERVER_STRING=mongo
  #     - DB_NAME=${DB_NAME}
  #     - TOKENS_COLLECTION_NAME=${TOKENS_COLLECTION_NAME}
  #     - SYNCS_COLLECTION_NAME=${SYNCS_COLLECTION_NAME}
  #     - HOLDINGS_COLLECTION_NAME=${HOLDINGS_COLLECTION_NAME}
  #     - CREDIT_COLLECTION_NAME=${CREDIT_COLLECTION_NAME}
  #     - MASTER_API_KEY=${MASTER_API_KEY}
    command: npm run dev
