name: ze-xe backend

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:  
  NODE_ENV: test
  MONGO_URL: mongodb+srv://g-2-project-1:AzVr1gDMWsMc1lAN@cluster0.j1yrl.mongodb.net/hardhat
  MONGO_URL1: mongodb+srv://g-2-project-1:AzVr1gDMWsMc1lAN@cluster0.j1yrl.mongodb.net/hardhat
  WEB_3_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweERjZTFjMzYxYzgyNEI1ZjRFMzRGY2ZCNjUxMUYzNjkwNjc5RjhmODYiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2Njk4OTQyMTQ5NjMsIm5hbWUiOiJ6ZXhlLjAxIn0.YR1oAHiW_tA0lwG29tXz2wrYdTjWdCijto4yP_3uHHg
  ADMIN_ADD: "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
  NETWORK: arbitrumGoerli  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
  
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: cd contracts && git checkout dev && npm install
      - run: cd contracts && npx hardhat compile
      # - run: npm install
      # - run: npx hardhat node
      # - run: npx hardhat test ../src/test/unitTestHardhat/**.ts --network localhost
      - run: |
          ls ${{github.workspace/contracts}}
      - run: |
          cd contracts && npx hardhat node &
          cd contracts && npx hardhat test ../src/test/unitTestHardhat/AorderScriptTest.ts --network localhost

